# The front repo is prior if conflicted
# CocoaPods private repo
source 'https://github.com/jcccn/PodSpecs.git'
# CocoaPods master repo
source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'BlocksKit'

pod 'MBProgressHUD'

pod 'Appirater'

pod 'JSONKit-NoWarning'

pod 'RETableViewManager', '~> 1.5.14'

pod 'OHAttributedLabel'

pod 'TimesSquare', :head

pod 'ShareSDK'

pod 'UMAnalytics'

pod 'UMFeedback'