source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'6.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'BlocksKit'

pod 'MBProgressHUD'

pod 'Appirater'

pod 'JSONKit-NoWarning'

pod 'RETableViewManager'

pod 'OHAttributedLabel'

pod 'TimesSquare', :head

pod 'ShareSDK/Normal', :git => 'https://github.com/jcccn/ShareSDK-iOS.git'

pod 'UMAnalytics', :git => 'https://github.com/jcccn/UMeng-Analytics-iOS.git'

pod 'UMFeedback', :git => 'https://github.com/jcccn/UMeng-Feedback-iOS.git'